//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public Nullable<int> Type { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string SecretWord { get; set; }
        public string SurName { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int GenderCode { get; set; }
        public string Post { get; set; }
        public byte[] UserImage { get; set; }
        public Nullable<bool> ApprovalStatus { get; set; }
        public Nullable<bool> AddData { get; set; }
        public Nullable<bool> ViewData { get; set; }
        public Nullable<bool> ReportGeneration { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual TypeUser TypeUser { get; set; }
    }
}
